### ISSUE TITLE
how to fix the "ghc --make site.hs" error?

### ISSUE THREAD

**Issue by luckypoem** [Libbum/AxiomaticSemantics#5]
hi.

root@AR:/usr/local/AxiomaticSemantics-site# ghc --make site.hs
[1 of 3] Compiling Includes.Pandoc  ( Includes/Pandoc.hs, Includes/Pandoc.o )

Includes/Pandoc.hs:8:1: error:
    Ambiguous interface for ‘Crypto.Hash’:
      it was found in multiple packages:
      cryptohash-0.11.9 cryptonite-0.20
root@AR:/usr/local/AxiomaticSemantics-site#

thank u.

**Comment by Libbum** [comment]
I use `cryptohash`. The quick and easy way to fix this is to run

`ghc-pkg hide cryptonite-0.20`

This sets the `exposed` flag for `cryptonite` to `False`. If you need `cyptonite` to be exposed all of the time, you may need to seek out a more permanent solution. But if this is fine for you, give it a shot and let me know how it goes.

**Comment by luckypoem** [comment]
thank u so much!it really works
