### ISSUE TITLE
Attribution in a derivative

### ISSUE THREAD

**Issue by deepfire** [Libbum/AxiomaticSemantics#7]
Tim, I have roughly stolen your layout in https://deepfire.github.io/

Please, tell me what I should change about it, so that it's ok with you:
- how I best attribute your work?
- should I change the color scheme?
- should I drop the starfield?
- should I drop the github recent activity widget?
- anything else?

/cc @Libbum

**Comment by Libbum** [comment]
Looks great! The lamba especially. I'm glad you like my theme and I'm happy for you to use it as is, feel free to keep anything you like and change stuff to suit you if it doesn't. 

If you'd like to put a like back to this repository somewhere that would be appreciated. It doesn't have to be prominent or even on your site - maybe just in the readme of your sites github repository.

**Comment by deepfire** [comment]
@Libbum, done -- at the bottom of every page you can now see a reference both to this repository and your blog! : -)

**Comment by deepfire** [comment]
Feel free to close this issue, if this is ok with you : -)

**Comment by Libbum** [comment]
Oh wow, thanks! Looking forward to reading what you're up to. Hope you manage to be a little more proactive about writing than I do with my blog :P

**Comment by deepfire** [comment]
I have never /really/ blogged before.. and now I can, from the comfort of org-mode -> the beautiful presentation that you and Hakyll provide..

Thank you!
